from scs_morph.claims.grouping import infer_roi_group


def test_grouping_examples():
    assert infer_roi_group("Left-Hippocampus", "fs8_subcortical_volume")["roi_group"] == "medial_temporal"
    assert infer_roi_group("Right-Amygdala", "fs8_subcortical_volume")["hemisphere"] == "RH"
    assert infer_roi_group("3rd-Ventricle", "fs8_subcortical_volume")["roi_group"] == "ventricle_csf"
    assert infer_roi_group("CC_Posterior", "fs8_subcortical_volume")["roi_group"] == "corpus_callosum"
    assert infer_roi_group("EstimatedTotalIntraCranialVol", "fs8_subcortical_volume")["roi_group"] == "global_brain_volume"
    assert infer_roi_group("lh_entorhinal", "fs8_cortical_volume")["roi_group"] == "temporal"
    assert infer_roi_group("rh_precuneus", "fs8_cortical_volume")["lobe"] == "parietal"
    assert infer_roi_group("lh_posteriorcingulate", "fs8_cortical_volume")["roi_group"] == "cingulate"
    assert infer_roi_group("rh_insula", "fs8_cortical_volume")["roi_group"] == "insula"
    assert infer_roi_group("LH_Default_Temp_1", "fs8_thickness_schaefer200_7")["network"] == "Default"
    assert infer_roi_group("RH_Cont_PFCl_1", "fs8_thickness_schaefer200_7")["anatomical_group"] == "prefrontal"
    assert infer_roi_group("LH_SalVentAttn_FrOperIns_1", "fs8_thickness_schaefer200_7")["anatomical_group"] == "operculo_insular"
    assert infer_roi_group("LH_VisCent_ExStr_1", "spm_thickness_schaefer200_17")["network_7_like"] == "Vis"
    assert infer_roi_group("RH_VisPeri_StriCal_1", "spm_thickness_schaefer200_17")["anatomical_group"] == "visual_occipital"
    assert infer_roi_group("LH_SomMotA_1", "spm_thickness_schaefer200_17")["network_7_like"] == "SomMot"
    assert infer_roi_group("RH_SomMotB_Aud_1", "spm_thickness_schaefer200_17")["anatomical_group"] == "auditory"
    assert infer_roi_group("LH_DorsAttnA_TempOcc_1", "spm_thickness_schaefer200_17")["network"] == "DorsAttnA"
    assert infer_roi_group("RH_DorsAttnB_PostC_1", "spm_thickness_schaefer200_17")["anatomical_group"] == "postcentral"
    assert infer_roi_group("LH_SalVentAttnA_Ins_1", "spm_thickness_schaefer200_17")["anatomical_group"] == "insula"
    assert infer_roi_group("RH_SalVentAttnB_PFCl_1", "spm_thickness_schaefer200_17")["network_7_like"] == "SalVentAttn"
    assert infer_roi_group("LH_LimbicA_TempPole_1", "spm_thickness_schaefer200_17")["anatomical_group"] == "temporal_pole"
    assert infer_roi_group("RH_LimbicB_OFC_1", "spm_thickness_schaefer200_17")["anatomical_group"] == "orbitofrontal"
    assert infer_roi_group("LH_ContA_IPS_1", "spm_thickness_schaefer200_17")["anatomical_group"] == "intraparietal_sulcus"
    assert infer_roi_group("RH_ContB_PFCld_1", "spm_thickness_schaefer200_17")["anatomical_group"] == "prefrontal"
    assert infer_roi_group("LH_DefaultA_pCunPCC_1", "spm_thickness_schaefer200_17")["anatomical_group"] == "precuneus_pcc"
    assert infer_roi_group("RH_DefaultC_PHC_1", "spm_thickness_schaefer200_17")["anatomical_group"] == "parahippocampal"
    assert infer_roi_group("LH_TempPar_1", "spm_thickness_schaefer200_17")["network"] == "TempPar"
    assert infer_roi_group("lh_17networks_LH_DefaultA_PCC", "fs8_thickness_kong200_17")["anatomical_group"] == "posterior_cingulate"
    assert infer_roi_group("rh_17networks_RH_ContA_IPS_1", "fs8_thickness_kong200_17")["network"] == "ContA"
    assert infer_roi_group("lh_17networks_LH_SalVenAttnB_Ins", "fs8_thickness_kong200_17")["anatomical_group"] == "insula"
    assert infer_roi_group("lh_lh_L_TP1_A", "fs8_thickness_yale696")["roi_group"] == "temporal_pole"
    assert infer_roi_group("rh_rh_R_MF1_A", "fs8_thickness_yale696")["hemisphere"] == "RH"
    assert infer_roi_group("lh_lh_L_CG_A", "fs8_thickness_yale696")["roi_group"] == "cingulate"
    assert infer_roi_group("rh_rh_R_I1_A", "fs8_thickness_yale696")["roi_group"] == "insula"

