CLAIM_TEMPLATES = {
    "diagnosis_contrast_composite": "{positive_label} is associated with {direction} {feature_family_label} in {region_summary} compared with {negative_label}, after adjustment for {covariate_text}.",
    "diagnosis_contrast_atomic_roi": "{positive_label} is associated with {direction} {roi} {feature_family_label} compared with {negative_label}, after adjustment for {covariate_text}.",
    "diagnosis_contrast_group_summary": "{positive_label}-versus-{negative_label} effects are concentrated in {group_label}, where {n_support_rois}/{n_group_rois} regions meet support criteria.",
    "diagnosis_contrast_ranking": "The top-ranked regions for the {positive_label}-versus-{negative_label} contrast are {top_regions}.",
    "cdr_impairment_contrast_composite": "CDR-defined cognitive impairment is associated with {direction} {feature_family_label} in {region_summary} compared with CDR 0, after adjustment for {covariate_text}.",
    "cdr_impairment_contrast_atomic_roi": "CDR-defined cognitive impairment is associated with {direction} {roi} {feature_family_label} compared with CDR 0, after adjustment for {covariate_text}.",
    "cdr_impairment_contrast_group_summary": "CDR-defined impairment effects are concentrated in {group_label}, where {n_support_rois}/{n_group_rois} regions meet support criteria.",
    "cdr_impairment_contrast_ranking": "The top-ranked regions for CDR-defined impairment are {top_regions}.",
    "mmse_association_composite": "Higher MMSE is associated with {direction} {feature_family_label} in {region_summary}, after adjustment for {covariate_text}.",
    "mmse_association_atomic_roi": "Higher MMSE is associated with {direction} {roi} {feature_family_label}, after adjustment for {covariate_text}.",
    "mmse_association_group_summary": "MMSE-associated effects are concentrated in {group_label}, where {n_support_rois}/{n_group_rois} regions meet support criteria.",
    "mmse_association_ranking": "The top-ranked regions for MMSE association are {top_regions}.",
    "age_association_composite": "Older age is associated with {direction} {feature_family_label} in {region_summary}, after adjustment for {covariate_text}.",
    "age_association_atomic_roi": "Older age is associated with {direction} {roi} {feature_family_label}, after adjustment for {covariate_text}.",
    "age_association_group_summary": "Age-associated effects are concentrated in {group_label}, where {n_support_rois}/{n_group_rois} regions meet support criteria.",
    "age_association_ranking": "The top-ranked regions for age association are {top_regions}.",
    "demographic_contrast_composite": "{positive_label} is associated with {direction} {feature_family_label} in {region_summary} compared with {negative_label}, after adjustment for {covariate_text}.",
    "demographic_contrast_atomic_roi": "{positive_label} is associated with {direction} {roi} {feature_family_label} compared with {negative_label}, after adjustment for {covariate_text}.",
    "demographic_contrast_group_summary": "Demographic contrast effects are concentrated in {group_label}, where {n_support_rois}/{n_group_rois} regions meet support criteria.",
    "demographic_contrast_ranking": "The top-ranked regions for the {positive_label}-versus-{negative_label} demographic contrast are {top_regions}.",
    "acquisition_contrast_composite": "{positive_label} acquisition is associated with {direction} {feature_family_label} in {region_summary} compared with {negative_label} acquisition, after adjustment for {covariate_text}.",
    "acquisition_contrast_atomic_roi": "{positive_label} acquisition is associated with {direction} {roi} {feature_family_label} compared with {negative_label} acquisition, after adjustment for {covariate_text}.",
    "acquisition_contrast_group_summary": "Acquisition-related effects are concentrated in {group_label}, where {n_support_rois}/{n_group_rois} regions meet support criteria.",
    "acquisition_contrast_ranking": "The top-ranked regions for the {positive_label}-versus-{negative_label} acquisition contrast are {top_regions}.",
    "continuous_association_composite": "{target_label} is associated with {direction} {feature_family_label} in {region_summary}, after adjustment for {covariate_text}.",
    "continuous_association_atomic_roi": "{target_label} is associated with {direction} {roi} {feature_family_label}, after adjustment for {covariate_text}.",
    "continuous_association_group_summary": "{target_label}-associated effects are concentrated in {group_label}, where {n_support_rois}/{n_group_rois} regions meet support criteria.",
    "continuous_association_ranking": "The top-ranked regions for association with {target_label} are {top_regions}.",
    "feature_ranking": "The top-ranked regions for {target_label} are {top_regions}.",
    "group_enrichment": "The claim signal is concentrated in {group_label}, where {n_support_rois}/{n_group_rois} regions meet support criteria.",
    "direction_summary_lower": "Across the support set, {fraction_pct}% of regions show lower {feature_family_label} for {target_label}.",
    "direction_summary_higher": "Across the support set, {fraction_pct}% of regions show higher {feature_family_label} for {target_label}.",
    "direction_summary_mixed": "The support set shows mixed directionality for {target_label}, suggesting heterogeneous regional effects.",
    "latent_morphometry_axis": "An unsupervised morphometry axis explains {explained_variance_pct}% of variance and is dominated by {top_regions}.",
    "latent_axis_association_continuous": "The unsupervised morphometry axis is associated with {metadata_variable} with correlation {association_value}.",
    "latent_axis_association_binary": "The unsupervised morphometry axis differs between {positive_label} and {negative_label} with standardized effect {association_value}.",
    "normative_deviation_composite": "{target_group} shows normative deviation in {feature_family_label}, most prominently in {region_summary}, relative to the {reference_group} reference.",
    "normative_deviation_atomic_roi": "{target_group} shows normative deviation in {roi} {feature_family_label} relative to the {reference_group} reference.",
    "normative_group_deviation": "{target_group} normative deviations are concentrated in {group_label}, where {n_support_rois}/{n_group_rois} regions exceed the deviation threshold.",
    "weak_support_notice": "This claim did not meet the predefined support threshold and should be treated as exploratory.",
}

